export const FETCH_DEPENDENCIES_LOADING = 'FETCH_DEPENDENCIES_LOADING';
export const FETCH_DEPENDENCIES_FAILURE = 'FETCH_DEPENDENCIES_FAILURE';
export const FETCH_DEPENDENCIES_SUCCESS = 'FETCH_DEPENDENCIES_SUCCESS';

export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const CLEAR_NODES = 'CLEAR_NODES';
